// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./internal/model/models.js";

/**
 * ApplyBuilderProposal validates the proposal again, replaces temporary
 * agent references with UUIDs, and commits the profiles and workflow together.
 */
export function ApplyBuilderProposal(request: model$0.BuilderApplyRequest): $CancellablePromise<model$0.BuilderApplyResult> {
    return $Call.ByID(3067082167, request);
}

export function CancelRun(runID: string): $CancellablePromise<void> {
    return $Call.ByID(56584525, runID);
}

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(2836621974);
}

export function Connect(): $CancellablePromise<void> {
    return $Call.ByID(4081416968);
}

export function CreateAgent(profile: model$0.AgentProfile): $CancellablePromise<model$0.AgentProfile> {
    return $Call.ByID(1165700971, profile);
}

export function CreateProject(project: model$0.Project): $CancellablePromise<model$0.Project> {
    return $Call.ByID(3582889279, project);
}

export function CreateSchedule(schedule: model$0.Schedule): $CancellablePromise<model$0.Schedule> {
    return $Call.ByID(1356601611, schedule);
}

export function DeleteAgent(agentID: string): $CancellablePromise<void> {
    return $Call.ByID(2103161718, agentID);
}

export function DeleteProject(projectID: string): $CancellablePromise<void> {
    return $Call.ByID(420456206, projectID);
}

export function DeleteSchedule(scheduleID: string): $CancellablePromise<void> {
    return $Call.ByID(3671430940, scheduleID);
}

export function DeleteWorkflow(workflowID: string): $CancellablePromise<void> {
    return $Call.ByID(3153398872, workflowID);
}

export function ExportProjectSnapshot(projectID: string): $CancellablePromise<string> {
    return $Call.ByID(623098869, projectID);
}

/**
 * GenerateBuilderProposal asks the shared Codex App Server for a declarative
 * proposal. It deliberately has no workspace roots and no tool allowlist, so
 * this conversation can plan changes but cannot execute them.
 */
export function GenerateBuilderProposal(request: model$0.BuilderRequest): $CancellablePromise<model$0.BuilderResponse> {
    return $Call.ByID(540849822, request);
}

export function GetActiveProject(): $CancellablePromise<model$0.Project> {
    return $Call.ByID(295685077);
}

export function GetAuthState(): $CancellablePromise<model$0.AuthState> {
    return $Call.ByID(4001352113);
}

export function GetDiagnostics(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1807514478);
}

export function GetRun(runID: string): $CancellablePromise<model$0.Run> {
    return $Call.ByID(2866079551, runID);
}

export function GetRunEvents(runID: string, afterSequence: number): $CancellablePromise<model$0.RunEvent[] | null> {
    return $Call.ByID(961779978, runID, afterSequence);
}

export function GetRuntimeStatus(): $CancellablePromise<model$0.RuntimeStatus> {
    return $Call.ByID(4176624);
}

export function ListAgents(): $CancellablePromise<model$0.AgentProfile[] | null> {
    return $Call.ByID(2029619840);
}

export function ListAudit(filter: model$0.AuditFilter): $CancellablePromise<model$0.AuditEntry[] | null> {
    return $Call.ByID(2840685313, filter);
}

export function ListHistory(filter: model$0.HistoryFilter): $CancellablePromise<model$0.HistoryEntry[] | null> {
    return $Call.ByID(2445116558, filter);
}

export function ListMCPServers(): $CancellablePromise<model$0.MCPServer[] | null> {
    return $Call.ByID(1027663362);
}

export function ListModels(): $CancellablePromise<model$0.ModelInfo[] | null> {
    return $Call.ByID(4263467744);
}

export function ListProjects(): $CancellablePromise<model$0.Project[] | null> {
    return $Call.ByID(933508140);
}

export function ListRuns(filter: model$0.RunFilter): $CancellablePromise<model$0.Run[] | null> {
    return $Call.ByID(2366263172, filter);
}

export function ListSchedules(): $CancellablePromise<model$0.Schedule[] | null> {
    return $Call.ByID(2857599552);
}

export function ListSystemPrompts(): $CancellablePromise<model$0.SystemPrompt[] | null> {
    return $Call.ByID(1431914634);
}

export function ListWorkflows(): $CancellablePromise<model$0.WorkflowDefinition[] | null> {
    return $Call.ByID(1869361628);
}

export function LoadWorkflow(workflowID: string): $CancellablePromise<model$0.WorkflowDefinition> {
    return $Call.ByID(134252323, workflowID);
}

export function LoginMCPServer(serverID: string): $CancellablePromise<string> {
    return $Call.ByID(4023574586, serverID);
}

export function PauseRun(runID: string): $CancellablePromise<void> {
    return $Call.ByID(2429326169, runID);
}

/**
 * PlanWithCodex keeps the user in a read-only conversation with a planning
 * lead before the configuration builder is asked to produce JSON. An
 * existing agent may supply the identity, role, model, and instructions, but
 * this turn never receives workspace roots or tools.
 */
export function PlanWithCodex(request: model$0.PlanningRequest): $CancellablePromise<model$0.PlanningResponse> {
    return $Call.ByID(1023814788, request);
}

export function ReloadMCPServers(): $CancellablePromise<void> {
    return $Call.ByID(1706455803);
}

export function ResetSystemPrompt(promptID: string): $CancellablePromise<model$0.SystemPrompt> {
    return $Call.ByID(2619055282, promptID);
}

export function ResolveApproval(decision: model$0.ApprovalDecision): $CancellablePromise<void> {
    return $Call.ByID(836263353, decision);
}

export function ResumeRun(runID: string): $CancellablePromise<void> {
    return $Call.ByID(1615000490, runID);
}

export function RetryStep(runID: string, stepID: string): $CancellablePromise<void> {
    return $Call.ByID(1604756378, runID, stepID);
}

export function RunTerminalCommand(projectID: string, command: string, workingDir: string): $CancellablePromise<model$0.TerminalResult> {
    return $Call.ByID(1782921556, projectID, command, workingDir);
}

export function SaveWorkflow(definition: model$0.WorkflowDefinition): $CancellablePromise<model$0.WorkflowDefinition> {
    return $Call.ByID(3881829630, definition);
}

/**
 * SelectProjectFolder opens the native folder picker and returns a validated
 * absolute path. An empty path means the user cancelled the dialog.
 */
export function SelectProjectFolder(): $CancellablePromise<string> {
    return $Call.ByID(1490459351);
}

export function SetActiveProject(projectID: string): $CancellablePromise<model$0.Project> {
    return $Call.ByID(3066739793, projectID);
}

export function StartRun(workflowID: string, input: { [_ in string]?: any } | null): $CancellablePromise<model$0.Run> {
    return $Call.ByID(1211922163, workflowID, input);
}

export function SteerRun(runID: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(3917714648, runID, message);
}

export function UpdateAgent(profile: model$0.AgentProfile): $CancellablePromise<model$0.AgentProfile> {
    return $Call.ByID(1953883728, profile);
}

export function UpdateProject(project: model$0.Project): $CancellablePromise<model$0.Project> {
    return $Call.ByID(1366100832, project);
}

export function UpdateSchedule(schedule: model$0.Schedule): $CancellablePromise<model$0.Schedule> {
    return $Call.ByID(4036507530, schedule);
}

export function UpdateSystemPrompt(promptID: string, template: string): $CancellablePromise<model$0.SystemPrompt> {
    return $Call.ByID(1251057976, promptID, template);
}

export function ValidateWorkflow(definition: model$0.WorkflowDefinition): $CancellablePromise<model$0.WorkflowValidation> {
    return $Call.ByID(508998961, definition);
}
