// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as model$0 from "../../../../RuanFernandes/centurion/internal/model/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "approval.requested": model$0.ApprovalRequest;
            "approval.resolved": model$0.ApprovalDecision;
            "auth.updated": model$0.AuthState;
            "builder.activity": model$0.BuilderActivityEvent;
            "codex.notification": model$0.CodexNotification;
            "mcp.status": model$0.MCPStatusEvent;
            "models.updated": model$0.ModelsUpdatedEvent;
            "office.agent.state": model$0.AgentStateEvent;
            "project.updated": model$0.Project;
            "run.created": model$0.Run;
            "run.event": model$0.RunEvent;
            "run.updated": model$0.RunUpdateEvent;
            "scheduler.updated": model$0.SchedulerEvent;
        }
    }
}
