// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AgentProfile {
    "id": string;
    "name": string;
    "role": string;
    "instructions": string;
    "modelID": string;
    "reasoningEffort": string;
    "workspaceRoots": string[] | null;
    "toolAllowlist": string[] | null;
    "approvalProfile": string;
    "roomID": string;
    "avatarID": string;
    "visualState": string;
    "maxDurationSeconds": number;
    "maxTurns": number;
    "maxAttempts": number;
    "memorySummary": string;
    "createdAt": string;
    "updatedAt": string;
}

export interface AgentStateEvent {
    "schemaVersion": number;
    "timestamp": string;
    "sequence": number;
    "source": string;
    "runID"?: string;
    "agentID": string;
    "state": string;
    "nodeID"?: string;
    "message"?: string;
}

export interface ApprovalDecision {
    "id": string;
    "decision": string;
}

export interface ApprovalRequest {
    "schemaVersion": number;
    "timestamp": string;
    "id": string;
    "kind": string;
    "title": string;
    "detail"?: string;
    "runID"?: string;
    "threadID"?: string;
    "turnID"?: string;
    "itemID"?: string;
    "choices"?: string[] | null;
    "expiresAt"?: string;
}

export interface AuthState {
    "status": string;
    "accountType"?: string;
    "email"?: string;
    "plan"?: string;
    "requiresOpenAIAuth": boolean;
    "rateLimit"?: RateLimitSnapshot | null;
    "error"?: string;
    "updatedAt": string;
}

/**
 * BuilderAgentDraft contains only declarative profile data. TemporaryID is
 * used for references inside the proposed workflow and is replaced by a
 * server-generated UUID when the proposal is applied.
 */
export interface BuilderAgentDraft {
    "temporaryID": string;
    "name": string;
    "role": string;
    "instructions": string;
    "modelID"?: string;
    "reasoningEffort"?: string;
    "workspaceRoots"?: string[] | null;
    "toolAllowlist"?: string[] | null;
    "approvalProfile": string;
    "roomID"?: string;
    "avatarID"?: string;
    "maxDurationSeconds"?: number;
    "maxTurns"?: number;
    "maxAttempts"?: number;
}

export interface BuilderApplyRequest {
    "projectID"?: string;
    "proposal": BuilderProposal;
}

export interface BuilderApplyResult {
    "agents": AgentProfile[] | null;
    "workflow"?: WorkflowDefinition | null;
}

/**
 * BuilderProposal is returned by Codex and remains inert until explicitly
 * applied by the user. Workflow references point to BuilderAgentDraft IDs.
 */
export interface BuilderProposal {
    "schemaVersion": number;
    "summary": string;
    "notes"?: string[] | null;
    "agents": BuilderAgentDraft[] | null;
    "workflow"?: WorkflowDefinition | null;
}

/**
 * BuilderRequest is the small, user-authored input sent to the in-app Codex
 * configuration builder. ThreadID is kept in memory by AppService so a
 * follow-up stays in the same builder conversation without exposing arbitrary
 * Codex threads to the frontend.
 */
export interface BuilderRequest {
    "prompt": string;
    "projectID"?: string;
    "threadID"?: string;
    "modelID"?: string;
    "reasoningEffort"?: string;
}

export interface BuilderResponse {
    "threadID": string;
    "reply": string;
    "proposal": BuilderProposal;
}

export interface CodexNotification {
    "schemaVersion": number;
    "timestamp": string;
    "sequence": number;
    "source": string;
    "method": string;
    "params"?: { [_ in string]?: any } | null;
}

export interface HistoryEntry {
    "id": string;
    "projectID"?: string;
    "kind": string;
    "title": string;
    "content"?: string;
    "metadata"?: { [_ in string]?: any } | null;
    "createdAt": string;
}

export interface HistoryFilter {
    "projectID"?: string;
    "kind"?: string;
    "limit"?: number;
}

export interface LoginStart {
    "type": string;
    "loginId"?: string;
    "authUrl"?: string;
    "verificationUrl"?: string;
    "userCode"?: string;
}

export interface MCPServer {
    "id": string;
    "name": string;
    "status": string;
    "authStatus"?: string;
    "tools"?: MCPTool[] | null;
    "resources"?: string[] | null;
    "error"?: string;
}

export interface MCPStatusEvent {
    "schemaVersion": number;
    "timestamp": string;
    "sequence": number;
    "source": string;
    "servers": MCPServer[] | null;
}

export interface MCPTool {
    "name": string;
    "description"?: string;
    "requiresApproval": boolean;
}

export interface ModelInfo {
    "id": string;
    "displayName": string;
    "description"?: string;
    "defaultReasoningEffort"?: string;
    "supportedReasoningEfforts"?: ReasoningEffort[] | null;
    "inputModalities"?: string[] | null;
    "supportsPersonality": boolean;
    "isDefault": boolean;
}

export interface ModelsUpdatedEvent {
    "schemaVersion": number;
    "timestamp": string;
    "sequence": number;
    "source": string;
    "models": ModelInfo[] | null;
}

/**
 * PlanningRequest is a user-authored message sent to the read-only planning
 * room. The selected agent contributes its identity and model, but the
 * service strips workspace and tool access before opening the Codex turn.
 */
export interface PlanningRequest {
    "prompt": string;
    "projectID"?: string;
    "threadID"?: string;
    "plannerAgentID"?: string;
    "modelID"?: string;
    "reasoningEffort"?: string;
}

export interface PlanningResponse {
    "threadID": string;
    "reply": string;
}

export interface Project {
    "id": string;
    "name": string;
    "description"?: string;
    "folders": string[] | null;
    "createdAt": string;
    "updatedAt": string;
    "lastOpenedAt"?: string;
}

export interface RateLimitBucket {
    "limitId"?: string;
    "limitName"?: string;
    "primary"?: RateLimitWindow | null;
    "secondary"?: RateLimitWindow | null;
    "rateLimitReachedType"?: string;
}

export interface RateLimitSnapshot {
    "limitId"?: string;
    "limitName"?: string;
    "usedPercent": number;
    "windowDurationMins": number;
    "resetsAt"?: number;
    "rateLimitReachedType"?: string;
    "secondary"?: RateLimitWindow | null;
    "buckets"?: RateLimitBucket[] | null;
}

export interface RateLimitWindow {
    "usedPercent": number;
    "windowDurationMins": number;
    "resetsAt"?: number;
}

export interface ReasoningEffort {
    "reasoningEffort": string;
    "description"?: string;
}

export interface RetryPolicy {
    "maxAttempts": number;
    "backoffSeconds": number;
    "idempotent": boolean;
}

export interface Run {
    "id": string;
    "projectID"?: string;
    "workflowID": string;
    "status": string;
    "input"?: { [_ in string]?: any } | null;
    "output"?: { [_ in string]?: any } | null;
    "currentNodeID"?: string;
    "startedAt": string;
    "updatedAt": string;
    "completedAt"?: string;
    "error"?: string;
    "cancelRequested": boolean;
    "paused": boolean;
}

export interface RunEvent {
    "schemaVersion": number;
    "timestamp": string;
    "sequence": number;
    "source": string;
    "runID": string;
    "type": string;
    "level": string;
    "nodeID"?: string;
    "agentID"?: string;
    "message": string;
    "data"?: { [_ in string]?: any } | null;
}

export interface RunFilter {
    "projectID"?: string;
    "workflowID"?: string;
    "status"?: string;
    "limit"?: number;
}

export interface RunUpdateEvent {
    "schemaVersion": number;
    "timestamp": string;
    "sequence": number;
    "source": string;
    "runID": string;
    "event": string;
    "runStatus"?: string;
}

export interface Schedule {
    "id": string;
    "name": string;
    "workflowID": string;
    "cron": string;
    "timezone": string;
    "enabled": boolean;
    "nextRunAt"?: string;
    "lastRunAt"?: string;
    "createdAt": string;
    "updatedAt": string;
}

export interface SchedulerEvent {
    "schemaVersion": number;
    "timestamp": string;
    "sequence": number;
    "source": string;
    "action": string;
    "scheduleID": string;
}

export interface SystemPrompt {
    "id": string;
    "name": string;
    "description": string;
    "template": string;
    "defaultTemplate": string;
    "variables": string[] | null;
    "isCustomized": boolean;
    "updatedAt"?: string;
}

export interface TerminalResult {
    "command": string;
    "workingDir": string;
    "output": string;
    "exitCode": number;
    "durationMs": number;
    "truncated": boolean;
}

export interface ValidationIssue {
    "code": string;
    "path"?: string;
    "message": string;
}

export interface WorkflowDefinition {
    "id": string;
    "name": string;
    "version": number;
    "description"?: string;
    "entryNodeID": string;
    "nodes": WorkflowNode[] | null;
    "edges": WorkflowEdge[] | null;
    "globalLimits": WorkflowLimits;
    "errorPolicy": string;
    "createdAt": string;
    "updatedAt": string;
}

export interface WorkflowEdge {
    "id": string;
    "from": string;
    "to": string;
    "condition"?: string;
}

export interface WorkflowLimits {
    "maxDurationSeconds": number;
    "maxParallel": number;
    "maxTurns": number;
}

export interface WorkflowNode {
    "id": string;
    "type": string;
    "label": string;
    "agentID"?: string;
    "condition"?: string;
    "toolName"?: string;
    "artifactPath"?: string;
    "maxIterations"?: number;
    "timeoutSeconds"?: number;
    "retry": RetryPolicy;
    "config"?: { [_ in string]?: any } | null;
}

export interface WorkflowValidation {
    "valid": boolean;
    "errors"?: ValidationIssue[] | null;
    "warnings"?: ValidationIssue[] | null;
}
