import { AppService as GeneratedAppService } from '../bindings/github.com/RuanFernandes/centurion'
import type {
  AgentProfile,
  AuditEntry,
  BuilderApplyRequest,
  BuilderApplyResult,
  BuilderRequest,
  BuilderResponse,
  PlanningRequest,
  PlanningResponse,
  ApprovalDecision,
  AuthState,
  HistoryEntry,
  MCPServer,
  ModelInfo,
  Project,
  Run,
  RunEvent,
  RuntimeStatus,
  Schedule,
  SystemPrompt,
  TerminalResult,
  WorkflowDefinition,
  WorkflowValidation,
  JsonMap,
} from './types'

const resolve = <T,>(value: unknown) => Promise.resolve(value as T)

export const api = {
  getAuthState: () => resolve<AuthState>(GeneratedAppService.GetAuthState()),
  listModels: () => resolve<ModelInfo[]>(GeneratedAppService.ListModels()),
  listSystemPrompts: () => resolve<SystemPrompt[]>(GeneratedAppService.ListSystemPrompts()),
  updateSystemPrompt: (promptID: string, template: string) => resolve<SystemPrompt>(GeneratedAppService.UpdateSystemPrompt(promptID, template)),
  resetSystemPrompt: (promptID: string) => resolve<SystemPrompt>(GeneratedAppService.ResetSystemPrompt(promptID)),
  listMCPServers: () => resolve<MCPServer[]>(GeneratedAppService.ListMCPServers()),
  loginMCPServer: (serverID: string) => resolve<string>(GeneratedAppService.LoginMCPServer(serverID)),
  reloadMCPServers: () => resolve<void>(GeneratedAppService.ReloadMCPServers()),
  listAgents: () => resolve<AgentProfile[]>(GeneratedAppService.ListAgents()),
  createAgent: (profile: AgentProfile) => resolve<AgentProfile>(GeneratedAppService.CreateAgent(profile)),
  updateAgent: (profile: AgentProfile) => resolve<AgentProfile>(GeneratedAppService.UpdateAgent(profile)),
  deleteAgent: (agentID: string) => resolve<void>(GeneratedAppService.DeleteAgent(agentID)),
  generateBuilderProposal: (request: BuilderRequest) => resolve<BuilderResponse>(GeneratedAppService.GenerateBuilderProposal(request)),
  planWithCodex: (request: PlanningRequest) => resolve<PlanningResponse>(GeneratedAppService.PlanWithCodex(request)),
  applyBuilderProposal: (request: BuilderApplyRequest) => resolve<BuilderApplyResult>(GeneratedAppService.ApplyBuilderProposal(request)),
  validateWorkflow: (definition: WorkflowDefinition) => resolve<WorkflowValidation>(GeneratedAppService.ValidateWorkflow(definition)),
  saveWorkflow: (definition: WorkflowDefinition) => resolve<WorkflowDefinition>(GeneratedAppService.SaveWorkflow(definition)),
  deleteWorkflow: (workflowID: string) => resolve<void>(GeneratedAppService.DeleteWorkflow(workflowID)),
  loadWorkflow: (workflowID: string) => resolve<WorkflowDefinition>(GeneratedAppService.LoadWorkflow(workflowID)),
  listWorkflows: () => resolve<WorkflowDefinition[]>(GeneratedAppService.ListWorkflows()),
  listProjects: () => resolve<Project[]>(GeneratedAppService.ListProjects()),
  getActiveProject: () => resolve<Project>(GeneratedAppService.GetActiveProject()),
  createProject: (project: Project) => resolve<Project>(GeneratedAppService.CreateProject(project)),
  updateProject: (project: Project) => resolve<Project>(GeneratedAppService.UpdateProject(project)),
  setActiveProject: (projectID: string) => resolve<Project>(GeneratedAppService.SetActiveProject(projectID)),
  deleteProject: (projectID: string) => resolve<void>(GeneratedAppService.DeleteProject(projectID)),
  listHistory: (filter: { projectID?: string; kind?: string; limit?: number } = {}) => resolve<HistoryEntry[]>(GeneratedAppService.ListHistory(filter)),
  listAudit: (filter: { projectID?: string; runID?: string; kind?: string; limit?: number } = {}) => resolve<AuditEntry[]>(GeneratedAppService.ListAudit(filter)),
  exportProjectSnapshot: (projectID = '') => resolve<string>(GeneratedAppService.ExportProjectSnapshot(projectID)),
  getRuntimeStatus: () => resolve<RuntimeStatus>(GeneratedAppService.GetRuntimeStatus()),
  runTerminalCommand: (projectID: string, command: string, workingDir: string) => resolve<TerminalResult>(GeneratedAppService.RunTerminalCommand(projectID, command, workingDir)),
  startRun: (workflowID: string, input: JsonMap) => resolve<Run>(GeneratedAppService.StartRun(workflowID, input)),
  pauseRun: (runID: string) => resolve<void>(GeneratedAppService.PauseRun(runID)),
  resumeRun: (runID: string) => resolve<void>(GeneratedAppService.ResumeRun(runID)),
  cancelRun: (runID: string) => resolve<void>(GeneratedAppService.CancelRun(runID)),
  retryStep: (runID: string, stepID: string) => resolve<void>(GeneratedAppService.RetryStep(runID, stepID)),
  steerRun: (runID: string, message: string) => resolve<void>(GeneratedAppService.SteerRun(runID, message)),
  getRun: (runID: string) => resolve<Run>(GeneratedAppService.GetRun(runID)),
  listRuns: (projectID = '') => resolve<Run[]>(GeneratedAppService.ListRuns({ projectID, limit: 50 })),
  getRunEvents: (runID: string, afterSequence: number) => resolve<RunEvent[]>(GeneratedAppService.GetRunEvents(runID, afterSequence)),
  resolveApproval: (decision: ApprovalDecision) => resolve<void>(GeneratedAppService.ResolveApproval(decision)),
  createSchedule: (schedule: Schedule) => resolve<Schedule>(GeneratedAppService.CreateSchedule(schedule)),
  updateSchedule: (schedule: Schedule) => resolve<Schedule>(GeneratedAppService.UpdateSchedule(schedule)),
  deleteSchedule: (scheduleID: string) => resolve<void>(GeneratedAppService.DeleteSchedule(scheduleID)),
  listSchedules: () => resolve<Schedule[]>(GeneratedAppService.ListSchedules()),
}
